version: "0.1"

services: 
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    command: yarn start
    ports: 
      - 3000:3000
    volumes: 
      - .:/usr/app
      - '/app/node_modules'
    depends_on: 
      - mysql_server
  
  mysql_server:
    image: mysql:8.0
    environment: 
      MYSQL_DATABASE: virtex_devops
      MYSQL_USER: virtex
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret

    volumes:
      - mysql_server:/var/lib/mysql
    restart: always

volumes:
  mysql_server: